### ISSUE TITLE
Crash on Motorola Pro+

### ISSUE THREAD

**Issue by olafhering** [gjedeer/mylocation#10]
Motorola Pro+, Android 2.3.6, installed from f-droid.app:

```
09-18 13:08:34.270   232   339 I ActivityManager: Starting: Intent { cmp=org.fdroid.fdroid/.AppDetails (has extras) } from pid 3061
09-18 13:08:34.340  3061  3061 I ToolbarWidgetWrapper: Progress display unsupported
09-18 13:08:34.480  3061  3061 W KeyCharacterMap: No keyboard for id -1
09-18 13:08:34.480  3061  3061 W KeyCharacterMap: No keyboard for id -1
09-18 13:08:34.480  3061  3061 W KeyCharacterMap: Can't open keycharmap file
09-18 13:08:34.480  3061  3061 W KeyCharacterMap: Using default keymap: /system/usr/keychars/qwerty.kcm.bin
09-18 13:08:34.560   301   301 D LatinKeyboard: updateF1Key-mIsAlphaKeyboard: true ,mHasVoiceButton: true
09-18 13:08:34.870   232   267 I ActivityManager: Displayed org.fdroid.fdroid/.AppDetails: +589ms
09-18 13:08:38.524   232   371 I ActivityManager: Starting: Intent { act=android.intent.action.MAIN flg=0x10000000 cmp=net.mypapit.mobile.myposition/.MyLocationActivity } from pid 3061
09-18 13:08:38.534   232   267 W ApplicationContext: Unable to create files directory
09-18 13:08:38.594   232   403 I ActivityManager: Start proc net.mypapit.mobile.myposition for activity net.mypapit.mobile.myposition/.MyLocationActivity: pid=3314 uid=10121 gids={}
09-18 13:08:38.794  3314  3314 W dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4001e560)
09-18 13:08:38.814  3314  3314 E AndroidRuntime: FATAL EXCEPTION: main
09-18 13:08:38.814  3314  3314 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{net.mypapit.mobile.myposition/net.mypapit.mobile.myposition.MyLocationActivity}: java.lang.NullPointerException
09-18 13:08:38.814  3314  3314 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1702)
09-18 13:08:38.814  3314  3314 E AndroidRuntime:        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:1727)
09-18 13:08:38.814  3314  3314 E AndroidRuntime:        at android.app.ActivityThread.access$1500(ActivityThread.java:124)
09-18 13:08:38.814  3314  3314 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:974)
09-18 13:08:38.814  3314  3314 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
09-18 13:08:38.814  3314  3314 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:130)
09-18 13:08:38.814  3314  3314 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:3859)
09-18 13:08:38.814  3314  3314 E AndroidRuntime:        at java.lang.reflect.Method.invokeNative(Native Method)
09-18 13:08:38.814  3314  3314 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Method.java:507)
09-18 13:08:38.814  3314  3314 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
09-18 13:08:38.814  3314  3314 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:647)
09-18 13:08:38.814  3314  3314 E AndroidRuntime:        at dalvik.system.NativeStart.main(Native Method)
09-18 13:08:38.814  3314  3314 E AndroidRuntime: Caused by: java.lang.NullPointerException
09-18 13:08:38.814  3314  3314 E AndroidRuntime:        at net.mypapit.mobile.myposition.MyLocationActivity.onCreate(MyLocationActivity.java:95)
09-18 13:08:38.814  3314  3314 E AndroidRuntime:        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1047)
09-18 13:08:38.814  3314  3314 E AndroidRuntime:        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:1666)
09-18 13:08:38.814  3314  3314 E AndroidRuntime:        ... 11 more
09-18 13:08:38.824   232   370 W ActivityManager:   Force finishing activity net.mypapit.mobile.myposition/.MyLocationActivity
09-18 13:08:38.824   232   370 W ActivityManager:   Force finishing activity org.fdroid.fdroid/.AppDetails
09-18 13:08:38.854   232   251 W ApplicationContext: Unable to create files directory
09-18 13:08:39.325   232   248 W ActivityManager: Activity pause timeout for HistoryRecord{40a64688 net.mypapit.mobile.myposition/.MyLocationActivity}
09-18 13:08:42.258   232   263 D BatteryTempPolicy: updateBatteryTemp temperature = 364, Threshhold = 3
09-18 13:08:42.268   232   276 D WifiService: getPersistedWifiEnabled : isSlot0Active false
```

Looks like `shareMessage` is NULL?

**Comment by gjedeer** [comment]
The stack trace this happened on startup, is that correct? Or after you pressed Share, as your message suggests?

**Comment by olafhering** [comment]
Its right after startup. Perhaps the app relies on an API which the Pro+ cant provide.

**Comment by gjedeer** [comment]
Hey, this looks like it didn't finish installing successfully. 

"Unable to create files directory" - strange

The line which triggers this problem is also rather unusual:

https://github.com/gjedeer/mylocation/blob/1.2.2/src/net/mypapit/mobile/myposition/MyLocationActivity.java#L95

I don't know why Android could create 3 resources but could not create the 4th...

**Comment by gjedeer** [comment]
Hey, this looks like it didn't finish installing successfully. 

"Unable to create files directory" - strange

The line which triggers this problem is also rather unusual:

https://github.com/gjedeer/mylocation/blob/1.2.2/src/net/mypapit/mobile/myposition/MyLocationActivity.java#L95

I don't know why Android could create 3 resources but could not create the 4th...

**Comment by olafhering** [comment]
Is the last type available only under certain conditions? Dont know enough about Android to debug it.
